# Generated by Django 5.1.14 on 2026-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("success", "Analysis Completed"),
                    ("error", "Analysis Failed"),
                    ("info", "Sample Submitted"),
                    ("warning", "System Alert"),
                ],
                max_length=20,
            ),
        ),
    ]
