# Generated by Django 5.1.14 on 2026-04-07 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization", models.CharField(blank=True, default="", max_length=200)),
                ("unit", models.CharField(blank=True, default="", max_length=200)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="profile/avatars/")),
                ("header", models.ImageField(blank=True, null=True, upload_to="profile/headers/")),
                ("notif_analysis", models.BooleanField(default=True)),
                ("notif_report", models.BooleanField(default=True)),
                ("notif_system", models.BooleanField(default=False)),
                ("display_compact", models.BooleanField(default=False)),
                ("display_timestamps", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="userprofile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
